#!/bin/bash

#TARGET=Debug
PROJECT="machoview.xcodeproj"
CONFIGURATION="Release"
SCHEME="MachOView"

BUILD_DIR=$(PWD)/build

if [[ -d $BUILD_DIR ]]; then
    rm -rf $BUILD_DIR
    echo "clean build dir ..."
fi

# clean
xcodebuild clean -project $PROJECT
# Build MachOView
xcodebuild build \
        -project $PROJECT \
        -scheme $SCHEME \
        -configuration $CONFIGURATION \
        SYMROOT=$(PWD)/build

if [[ $? != 0 ]]; then
    echo "build failure: exit code $?"
    exit 0
fi
# Create DMG Installer
cp -f ./Applications $BUILD_DIR/$CONFIGURATION/Applications
buildPlist=$BUILD_DIR/$CONFIGURATION/$SCHEME.app/Contents/Info.plist
CFBuildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBuildNumber" $buildPlist)
CFBundleShortVersionString=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" $buildPlist)
cp -f README $BUILD_DIR/$CONFIGURATION

hdiutil create \
    -fs HFS+ \
    -volname "$SCHEME" \
    -srcfolder $BUILD_DIR/$CONFIGURATION \
    "MachOView-"$CFBundleShortVersionString.$CFBuildNumber".dmg"
